import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home() {
  const [title, setTitle] = useState('');
  const [movies, setMovies] = useState({
    value: '',
    list: []
  });
  const [nominations, setNominations] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  
  const handleSubmit = async (event) => {
    event.preventDefault()
    setLoading(true);
    const searchValue = title;
    // fetch(`http://www.omdbapi.com/apikey=${process.env.API_KEY}&t=${title}`)
    fetch(`http://www.omdbapi.com/?apikey=8154a0e3&type=movie&s=${title}`)
    .then((response) => {
      return response.json()
    })
    .then((data) => {
      if (data.Response.includes('False')){
        setError(data.Error);
      } else {
        setError('');
      }
      setMovies({ value: searchValue, list: data.Search });
      setLoading(false);
    })
    .catch((err) => {
      alert(err)
      setLoading(false)
      setError('Error Submitting')
    })
  }

  const handleInputChange = (e) => {
    setTitle(e.target.value)
  }

  const addNomination = () => {
    let errors = [];
    if (nominations.length >= 5) {
      return errors.push('You Have Already Selected 5 Movies')
    }
    if (nominations.some((nominatedMovie) => nominatedMovie.imdbID == movie.imdbID)) {
      errors.push('This Movie Has Already Been Nominated')
    }
    errors.length ? 
      alert(errors)
      : setNominations(prevNominations => {
        return [...prevNominations, movie]
      })
  }

  let nominationContent = <p>No Nominations Selected</p>

  if (nominations.length > 0) {
    nominationContent = (
    <ul>
      {nominations.map((movie) => {
        return <li>{movie.Title}</li>
      })}
    </ul>
    )
  }

  return (
    <div className="h-screen flex flex-col justify-start items-center bg-body-bg">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col flex-1 justify-around items-center w-4/5">
        <h1 className="m-2 text-center">Search For A Movie</h1>
        <div className="w-full max-w-lg">
        <form onSubmit={handleSubmit} className="w-full max-w-xl p-2 border sm:p-4">
          <div>
        <label htmlFor="title" className="font-bold">
          Movie Title
        </label>
          <input type="text" name="title" id="title" placeholder="Enter a Movie Title" value={title} onChange={handleInputChange} className="bg-white focus:outline-none focus:shadow-outline border border-gray-300 rounded-lg py-2 px-4 my-2 block w-full appearance-none leading-normal"/>
          </div>
          <button type="submit" className="bg-green-600 hover:bg-green-700 text-white font-bold py-1.5 px-3 rounded">{!loading ? "Submit" : "Poooop"}</button>
          </form>
          <p className="text-center my-2">{error}</p>
          <div>
          {movies?.list ? <h2>Search Results for "{movies.value}"</h2> : null }
          </div>
        </div>

        <div className="overflow-y-scroll h-64">
        {movies?.list?.length > 0 && movies.list.map((movie) => {
          return (
          <div className="bg-gray-200 p-4 m-1">
            {/* <Image src={movie.Poster} alt={`Movie Poster`} width={24} height={36}></Image> */}
            <p>{movie.Title}</p>
            <p>{movie.Year}</p>
            <button onClick={addNomination}>Nominate</button>
          </div>)
        })
        }
        </div>
        <div>
          <h2>Saved Nominations</h2>
          {nominationContent}
        </div>
      </main>
      <footer className="w-full h-24 flex justify-center items-center items-center border-t">
        <a
          href="https://www.omdbapi.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by the <strong>ODDB Api</strong>{' '}
          <span className="">
            <Image src="/favicon.ico" alt="Vercel Logo" width={16} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
